//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by GitVersion.
// 
// You can modify this code as we will not overwrite it when re-executing GitVersion
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyFileVersion("4.1.0.0")]
[assembly: AssemblyVersion("4.1.0.0")]
[assembly: AssemblyInformationalVersion("4.1.0-alpha+100.Branch.master.Sha.91575d32affcc335cfa9a52b2b5f4ff4b0afdf49")]